apiVersion: v1
kind: Service
metadata:
  name: devops-demo-app
  namespace: demo
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: devops-demo-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: devops-demo-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo-app
  template:
    metadata:
      labels:
        app: devops-demo-app
    spec:
      containers:
      - name: devops-demo-app
        image: mycluster.icp:8500/demo/devops-demo-app:0.4
        ports:
        - containerPort: 9080
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_VERSION
          value: "0.4"
        - name: POD_ENVIRONMENT
          value: "GREEN"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: devops-demo-app
 namespace: demo
spec:
  rules:
  - http:
      paths:
      - path: /demo
        backend:
         serviceName: devops-demo-app
         servicePort: 9080